Official name change
flybywiresim/simbridge pull request #11
Opened 2022-04-17 16:00 UTC by Lucky38i

- packaged exe name now appropriate
- refactored releases to accomodate new name
- new name added in other areas where needed

2022-05-17 21:30 UTC, FoxtrotSierra6829 requested changes
while `./` might not always be required as a prefix on relative paths, it's just better practice to always use it

2022-05-17 21:31 UTC, Lucky38i commented
> while `./` might not always be required as a prefix on relative paths, it's just better practice to always use it

The GHA are ran in windows servers, should I still add the ./?

2022-05-17 21:35 UTC, FoxtrotSierra6829 commented
> The GHA are ran in windows servers, should I still add the ./?

yeah noticed this. IMO yes, I think it's better practice to use them both on Linux and Windows.

2022-05-17 21:36 UTC, Lucky38i commented on .github/workflows/release.yml
> +          node scripts\cdn.js
Not sure what you mean. Add the ./ here too?

2022-05-17 22:48 UTC, FoxtrotSierra6829 commented on .github/workflows/release.yml
> +          node scripts\cdn.js
no the fact that you're calling `cdn.js` within "Build ZIP File". I assume it should be `fragment.js` since you never called that anywhere else?

2022-05-25 23:55 UTC, Benjozork approved these changes

2022-05-27 01:24 UTC, FoxtrotSierra6829 commented on package.json
> +		"npm": "7.x.x"
current Node LTS version is shipped with npm 8.5.5

2022-05-29 17:11 UTC, FoxtrotSierra6829 submitted a review, later dismissed

2022-05-29 17:11 UTC, FoxtrotSierra6829 commented on package.json
> +		"npm": "7.24.x"
as mentioned previously, you need NPM version >=8.5.5, else it's just gonna fail the workflow.

![grafik](https://user-images.githubusercontent.com/50082450/170882808-c2dd43ad-f6c9-40b7-b23e-1a2f2ba82ad9.png)
(using exactly the same workflow as here until after set node version)

2022-06-01 22:47 UTC, FoxtrotSierra6829 approved these changes

2022-06-01 22:49 UTC, merged