fix: address inproper path joining
flybywiresim/simbridge pull request #41
Opened 2022-08-29 02:46 UTC by leon332157

Attempt to fix #30

2022-08-29 11:26 UTC, Lucky38i requested changes
LGTM, tested a bundle. Only thing is can you make `checkFilePathSafety` throw the `422` status code. This is done until I can get around to setting up a proper error handler. 

Example: https://github.com/flybywiresim/simbridge/blob/5f69e4b25e23304edcd15122e7cbaf979ba006bd/apps/server/src/utilities/file.service.ts#L29

2022-08-29 14:07 UTC, Benjozork commented
Oops, this is what I get for forgetting to make a PR.

I did it in the `bugs/30/path-issue` branch. You must also remove `..` segments to prevent directory traversal.

2022-08-29 14:09 UTC, Benjozork requested changes

2022-08-29 14:09 UTC, Benjozork commented on apps/server/src/utilities/file.service.ts
> +            const dir = join(process.cwd(), <string>directory);
**suggestion:** let's move all of that to use `string` as the argument and not `PathLike`. I see no circumstance in which we will use a `Buffer` as a parameter to this function :smile:

2022-08-31 10:43 UTC, Lucky38i approved these changes

2022-09-09 03:12 UTC, Benjozork approved these changes

2022-09-17 13:58 UTC, merged